#!/usr/bin/env node
// Reads every art/*.json sprite grid and generates the corresponding box-shadow CSS as SCSS
// partials in styles/sprites/. Run via `npm run build:sprites` -- see README.md.

import { mkdirSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gridToBoxShadow, loadAllSpriteRecords, PALETTE_ENTRIES } from "./lib/pixel-grid.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPRITES_DIR = join(ROOT, "styles", "sprites");
const ABSTRACTS_DIR = join(ROOT, "styles", "abstracts");

function loadSprites() {
  return loadAllSpriteRecords().sort((a, b) => a.name.localeCompare(b.name));
}

function scssFor(sprite) {
  const entries = gridToBoxShadow(sprite);
  const body = entries.length > 0 ? entries.join(",\n    ") : "none";
  return `// GENERATED by scripts/build-sprites.mjs from art/${sprite.name}.json -- do not hand-edit.
.sprite-${sprite.name} {
  box-shadow:
    ${body};
}
`;
}

function paletteTokensScss() {
  const lines = PALETTE_ENTRIES.map((e) => `  ${e.cssVar}: ${e.hex};`).join("\n");
  return `// GENERATED by scripts/build-sprites.mjs from art/legend.json + art/palette.hex --
// do not hand-edit.
:root {
${lines}
}
`;
}

// Deletes any styles/sprites/_<name>.scss that no longer has a matching art/<name>.json --
// otherwise a deleted/renamed sprite leaves stale generated CSS behind indefinitely (only
// _index.scss's forward list gets regenerated fresh each run; the individual partials don't get
// cleaned up on their own).
function pruneOrphanedPartials(sprites) {
  const expected = new Set(sprites.map((s) => `_${s.name}.scss`));
  const existing = readdirSync(SPRITES_DIR).filter(
    (f) => f.startsWith("_") && f.endsWith(".scss") && f !== "_index.scss",
  );
  for (const file of existing) {
    if (!expected.has(file)) {
      unlinkSync(join(SPRITES_DIR, file));
      console.log(`Removed orphaned ${join(SPRITES_DIR, file)} (no matching art/*.json)`);
    }
  }
}

function main() {
  mkdirSync(SPRITES_DIR, { recursive: true });
  mkdirSync(ABSTRACTS_DIR, { recursive: true });
  const sprites = loadSprites();

  const paletteOutPath = join(ABSTRACTS_DIR, "_palette-tokens.scss");
  writeFileSync(paletteOutPath, paletteTokensScss());
  console.log(`Wrote ${paletteOutPath} (${PALETTE_ENTRIES.length} colors)`);

  pruneOrphanedPartials(sprites);

  for (const sprite of sprites) {
    const outPath = join(SPRITES_DIR, `_${sprite.name}.scss`);
    writeFileSync(outPath, scssFor(sprite));
    console.log(`Wrote ${outPath}`);
  }

  // Always rewrite _index.scss, even with zero sprites -- otherwise removing the last sprite
  // prunes its orphaned partial (above) but leaves _index.scss's @forward pointing at the now-
  // deleted file, breaking the next `sass` compile for anyone consuming this output.
  const indexPath = join(SPRITES_DIR, "_index.scss");
  const forwards = sprites.map((s) => `@forward "${s.name}";`).join("\n");
  // $available-sprites lets other SCSS check whether a given sprite's art exists yet and fall
  // back to something else if not -- so drawing and saving a new sprite is the only step needed;
  // the next `npm run build:sprites` picks it up with no further hand-edits.
  const namesList = sprites.map((s) => `"${s.name}"`).join(", ");
  writeFileSync(
    indexPath,
    `// GENERATED by scripts/build-sprites.mjs -- do not hand-edit.\n${forwards}\n\n` +
      `$available-sprites: (${namesList}) !default;\n`,
  );
  console.log(`Wrote ${indexPath} (${sprites.length} sprite${sprites.length === 1 ? "" : "s"})`);
}

main();
